# Generated by Django 5.2.4 on 2025-08-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('BANK', 'Bank'), ('CREDITCARD', 'Credit Card')], max_length=16)),
                ('bank_id', models.CharField(blank=True, max_length=64, null=True)),
                ('account_id', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('type', 'bank_id', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitid', models.CharField(max_length=128)),
                ('posted_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trntype', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('memo', models.CharField(blank=True, max_length=512)),
                ('checknum', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finwise_app.account')),
            ],
            options={
                'ordering': ['-posted_date', '-id'],
                'unique_together': {('account', 'fitid')},
            },
        ),
    ]
