# Generated by Django 5.2.5 on 2025-10-13 06:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finwise_app', '0003_account_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bill name or payee', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Additional notes about this bill')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bill amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(help_text='When the bill is due')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One-time')], default='MONTHLY', help_text='How often this bill repeats', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the bill', max_length=16)),
                ('reminder_days', models.PositiveIntegerField(default=3, help_text='How many days before due date to send reminder')),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('auto_pay_account', models.ForeignKey(blank=True, help_text='Account to auto-pay from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_pay_bills', to='finwise_app.account')),
                ('category', models.ForeignKey(blank=True, help_text='Category for expense tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='finwise_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'name'],
                'indexes': [models.Index(fields=['user', 'due_date'], name='finwise_app_user_id_fb2a72_idx'), models.Index(fields=['user', 'status'], name='finwise_app_user_id_cc8f97_idx')],
            },
        ),
    ]
