# Generated by Django 5.2.5 on 2025-10-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finwise_app', '0004_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='auto_pay_account',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='auto_pay_enabled',
        ),
    ]
