# Generated by Django 5.2.5 on 2025-10-17 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finwise_app', '0005_remove_bill_auto_pay_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('user', 'type', 'bank_id', 'account_id')},
        ),
    ]
