# Generated by Django 5.2.5 on 2025-11-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finwise_app', '0006_alter_account_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('BUDGET', 'Spending Limit'), ('GOAL', 'Savings Goal')], default='BUDGET', help_text='Budget = spending limit, Goal = savings target', max_length=10),
        ),
    ]
